[package]
name = "mediabrowser"
version = "0.1.0"
edition = "2021"

[features]
default = ["api", "ui"]
httpd = ["dep:tokio-util"]
api = ["dep:tar", "dep:tokio-util", "tokio/sync"]
ui = ["api", "dep:flate2"]

[dependencies]
tokio = { version = "1.0", default-features = false, features = ["rt", "fs", "io-util", "net", "signal"] }
tokio-util = { version = "0.7", default-features = false, features = ["io"], optional = true }
hyper = { version = "1", default-features = false, features = ["http1", "server"] }
hyper-util = { version = "0.1", default-features = false, features = ["http1", "server", "server-graceful", "tokio"] }
http-body = "1"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
percent-encoding = { version = "2.3", default-features = false, features = ["alloc"] }
bytes = { version = "1.0", default-features = false }
tar = { version = "0.4", default-features = false, optional = true }

[build-dependencies]
flate2 = { version = "1", default-features = false, features = ["rust_backend"], optional = true }

[dev-dependencies]
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }

[profile]

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
