[package]
name = "mediabrowser"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", default-features = false, features = ["rt-multi-thread", "fs", "io-util", "net", "signal", "sync"] }
tokio-util = { version = "0.7", default-features = false, features = ["io"] }
hyper = { version = "1", default-features = false, features = ["http1", "server"] }
hyper-util = { version = "0.1", default-features = false, features = ["http1", "server", "server-graceful", "tokio"] }
http-body-util = "0.1"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
percent-encoding = { version = "2.3", default-features = false, features = ["alloc"] }
bytes = { version = "1.0", default-features = false }
tar = { version = "0.4", default-features = false }
walkdir = { version = "2.5.0", default-features = false }

[profile]

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
