services:

  pro:
    build: .
    ports:
      - "30003:30003"
    volumes:
      - ./data:/data
    restart: unless-stopped
    environment:
      - RUST_LOG=info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30003/ui"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - pro

  dev:
    image: docker.io/library/rust:latest
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        apt-get update && apt-get install -y pkg-config libssl-dev
        cargo install cargo-watch
        cargo watch -x run
    working_dir: /app
    volumes:
      - ./Cargo.toml:/app/Cargo.toml
      - ./Cargo.lock:/app/Cargo.lock
      - ./src:/app/src
      - ./static:/app/static
      - ./data:/data
    ports:
      - "30003:30003"
    environment:
      - RUST_LOG=debug
    profiles:
      - dev
