services:

  pro:
    build:
      context: .
      args:
        FEATURES: ${FEATURES:-api,ui}
    ports:
      - "30003:30003"
    volumes:
      - ./data:/data:z
    restart: unless-stopped
    environment:
      - BIND_ADDR=0.0.0.0
      - TLS_HOSTS=${TLS_HOSTS:-localhost,127.0.0.1}
    profiles:
      - pro

  dev:
    image: docker.io/library/rust:1.94.1-alpine
    entrypoint: ['/bin/sh', '-c']
    command:
      - |
        apk add --no-cache musl-dev
        cargo install cargo-watch
        cargo watch -x "run --no-default-features --features $$FEATURES"
    working_dir: /app
    # build:
    #   dockerfile: ./Dockerfile
    #   context: .
    #   # args:
    #   #   FEATURES: httpd
    volumes:
      - ./Cargo.toml:/app/Cargo.toml:z
      - ./Cargo.lock:/app/Cargo.lock:z
      - ./build.rs:/app/build.rs:z
      - ./src:/app/src:z
      - ./data:/data:z
    ports:
      - "30003:30003"
    environment:
      - FEATURES=${FEATURES:-api,ui}
      - BIND_ADDR=0.0.0.0
      - TLS_HOSTS=${TLS_HOSTS:-localhost,127.0.0.1}
    profiles:
      - dev
